### ISSUE TITLE
PARTE 3: SPRINT I (25/6 - 22/7)

### ISSUE THREAD

**Issue by evaesqmor** [evaesqmor/McFly-Cinema-Bot#11]
- [ ] Aprendizaje sobre chatbots y su creación
- [ ] Decisión sobre el entorno de despliegue (Telegram, Discord)
-----------------------------------------
**Implementación de primeras características**
- [ ] Compra de entradas
------------------------------------------
- [ ] **Sprint 1** 
Requisitos 
Diseño 
Implementación 
Pruebas 
Resumen 
------------------------------------------
 **Manual de instalación** 
- [ ] Requisitos hardware 
- [ ] Requisitos software 
- [ ] Proceso de instalación 
------------------------------------------
**Manual de usuario**
- [ ] Manual de usuario 
- [ ] Manual de administrador
