### ISSUE TITLE
PARTE 2: PLANIFICACIÓN (18/6 - 24/6)

### ISSUE THREAD

**Issue by evaesqmor** [evaesqmor/McFly-Cinema-Bot#14]
**PARTE 1 Doc: Planificación**
- [x] Planificación temporal
- [ ] Planificación de costes
-----------------------------------------

**PARTE 2 Doc: Materias relacionadas**
- [ ] Metodología SCRUM
- [x] Descripción de las tecnologías Web

------------------------------------------
**PARTE 3 Doc: Diseño Inicial** 
- [ ] Objetivos 
- [ ] Requisitos del producto 
- [ ] Prototipos 
- [ ] Arquitectura 
- [ ] Sprints
