### ISSUE TITLE
PARTE 1: INICIACIÓN (10/6 - 17/6) 

### ISSUE THREAD

**Issue by evaesqmor** [evaesqmor/McFly-Cinema-Bot#6]
- [x] Esquema BPMN proyecto
- [x] Decisión de APIS 
---------------------------------------------------------------------
PARTE 1 Doc: Introducción
- [x] Motivación
- [x] Objetivos del proyecto
- [x] Estructura del documento
